### PR TITLE
more tests

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by stereobooster** [comment]
@peterbe good for review. I will add more later

**Comment by stereobooster** [comment]
should we remove `examples` folder?

**Comment by peterbe** [comment]
You're amazing @stereobooster !

**Comment by peterbe** [comment]
> should we remove examples folder?

Yes. It's confusing that it's there if we're not actively using it. 
It would be nice to document how you can use `tests/examples` when debugging outside of running unit tests. I for one, open a separate terminal and go into the `examples` directory and run `http-server` and then test minimalcss against `localhost:8080/...`.

**Comment by stereobooster** [comment]
I wanted to merge other pr and rebase this one, but erased history instead

**Comment by stereobooster** [comment]
I will restore it later

**Pull request closed without merging**
