### PR TITLE
upgrade puppeteer to 1.0.0

### PR DESCRIPTION
**Pull request by jonathaningram**
First pass, not sure if I've missed anything...

Release notes: https://github.com/GoogleChrome/puppeteer/releases/tag/v1.0.0

### CODE REVIEW

**Comment by peterbe** [comment]
Not sure what's going on [with travis](https://travis-ci.org/peterbe/minimalcss/builds/329648323) but I can't open the log to see what went wrong there. 

This PR is great! I'm looking forward to landing it. But I'm going to focus on https://github.com/peterbe/minimalcss/pull/73 first.

**Comment by peterbe** [comment]
[Just says "null"](https://api.travis-ci.org/v3/job/329648324/log.txt)

**Comment by peterbe** [comment]
Closing/Opening to tell Travis to try again.

**Comment by peterbe** [comment]
@jonathaningram Would you mind rebasing it up and try again?

**Comment by jonathaningram** [comment]
@peterbe thanks. Rebased and Travis is fixed. FYI when I checked yesterday Travis was having issues, so that's probably why the build never finished.

**Comment by jonathaningram** [comment]
No worries @peterbe I'm glad to help. It was a pretty easy change! Agree, hopefully there's more value I can add.

**Pull request merged**
