### PR TITLE
Fix get params for urls in css

### PR DESCRIPTION
**Pull request by usebaz**
Fix for issue #147

### CODE REVIEW

**Comment by stereobooster** [comment]
Hi. Thank you for contribution. Can you please add test for this functionality?

**Comment by usebaz** [comment]
@stereobooster When will you be able to merge and release a new version of the package?

**Comment by stereobooster** [comment]
I can merge, but we need to wait @peterbe to release it

**Comment by usebaz** [comment]
@peterbe can you release new version with this fix?

**Pull request merged**
