### PR TITLE
add CSSO options

### PR DESCRIPTION
**Pull request by usebaz**
Hi,
In some cases need change default CSSO options. Example for delete comments from minimal css.

### CODE REVIEW

**Comment by usebaz** [comment]
I test locally. Build failing in your master.

**Comment by stereobooster** [comment]
I just merged branch, which should fix tests. You can rebase

**Comment by peterbe** [comment]
Hi @usebaz I don't even know how this happens but this diff looks like it's changing things that were already changed in master. 
I like the new feature though! It's going to need to work on the command line too for this to be ready to merge.

**Comment by usebaz** [comment]
I only make rebase from upstream/master. Maybe you add command line support
in other PR or commit. I add functionality and tests

ср, 21 бер. 2018, 21:28 користувач Peter Bengtsson <notifications@github.com>
пише:

**Comment by peterbe** [comment]
Can you try to rebase this against the latest master?

**Comment by usebaz** [comment]
I try and it seems to be correct =)

**Comment by peterbe** [comment]
Since it's a new feature I made a new release. Since it's not breaking anything I made it a patch release: https://github.com/peterbe/minimalcss/releases/tag/v0.7.5

THANK YOU @usebaz for helping out! Please come back and hang out and help out some more.

**Comment by usebaz** [comment]
Thank you to. I necessarily come back)

пт, 23 бер. 2018, 18:55 користувач Peter Bengtsson <notifications@github.com>
пише:

**Pull request merged**
