### PR TITLE
Strip font faces not used fixes 55

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
@stereobooster Would you mind taking this for a test drive? It certainly looks to work with the `examples/fonts/index.html` I added. 

I tried with against my own blog since it uses SemanticUI which has a bunch of font families in it. 
Once on the `master` branch:
```
▶ ./bin/minimalcss.js -d -o /tmp/peterbe.before.css https://www.peterbe.com/search\?q\=searching
```
Once on this branch:
```
▶ ./bin/minimalcss.js -d -o /tmp/peterbe.after.css https://www.peterbe.com/search\?q\=searching
```
And compare the difference:
```
▶ ls -lh /tmp/peterbe*.css
-rw-r--r--  1 peterbe  wheel    27K Jan 19 16:51 /tmp/peterbe.after.css
-rw-r--r--  1 peterbe  wheel    56K Jan 19 16:51 /tmp/peterbe.before.css
```
Wohoo! That's a saving of 29KB!

**Comment by peterbe** [comment]
@lahmatiy I'm not sure how to credit you for this code and help. 
In [this comment](https://github.com/peterbe/minimalcss/pull/73#issuecomment-358363179) you pointed to a [branch](https://github.com/lahmatiy/penthouse/blob/master/src/postformatting/unused-fontface-remover.js) you have for penthouse. I copied that code and styled it up a bit differently. 

The simplest solution might be to, formally, ask: Are you ok with me including the code you wrote from `unused-fontface-remover.js`?

**Comment by lahmatiy** [comment]
@peterbe Don't not worry about credits. Feel free to use it as you want. It's open source ;)

**Comment by stereobooster** [comment]
As soon as we get https://github.com/peterbe/minimalcss/pull/85 merged we can start write tests

**Pull request merged**
