### PR TITLE
Update puppeteer to 1.2

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by peterbe** [comment]
What happened to the PR Renovate would make? That has a link to the changelog.

**Comment by stereobooster** [comment]
> What happened to the PR Renovate would make?

It updated `@types/puppeteer` but not `puppeteer`, so I closed it and made this instead

**Comment by peterbe** [comment]
But that only updated the types definition. [It](https://github.com/peterbe/minimalcss/pull/156/files) didn't upgrade `package.json`. 

Either way, I'll have to check out what the new features and changes are in 1.2 and see how it relates to us.

**Comment by peterbe** [comment]
It seems there are no scary API changes in [1.2](https://github.com/GoogleChrome/puppeteer/releases/tag/v1.2.0)

**Comment by stereobooster** [comment]
I'm not sure when you want to release. I merged  two PRs. You can merge this when you want

**Comment by peterbe** [comment]
I'll make a release tomorrow if time allows.

**Comment by peterbe** [comment]
[0.7.4 released](https://github.com/peterbe/minimalcss/releases/tag/v0.7.4)

**Comment by stereobooster** [comment]
Didn't we introduced breaking change for `withoutjavascript`?

**Comment by peterbe** [comment]
Dang! You're probably right. Sorry. I guess it should have become 0.8.0. I failed. But I'm struggling to find the time to fix that right now.

**Comment by stereobooster** [comment]
Happens. Please don't worry about it ❤️

**Pull request merged**
