### PR TITLE
[#62] trying CSS.takeCoverageDelta

### PR DESCRIPTION
**Pull request by stereobooster**
Not all tests pass, because there are issues in chrome CSS coverage. I just want to show you that this is possible. As soon as they will fix chrome bugs we can simplify `minimalcss` a lot.

Take a look and close it.

### CODE REVIEW

**Comment by peterbe** [comment]
I didn't read it super carefully but I saw you commented out the page load with javascript disabled. 
Is that deliberate or is not going to be possible if you use the devtools?

I'm quite excited about the idea of it giving a minimal CSS based on ALL CSS loaded into memory and not just the external CSS.

**Comment by peterbe** [comment]
So what's the Chrome bug to pin this to?

**Comment by stereobooster** [comment]
> I didn't read it super carefully but I saw you commented out the page load with javascript disabled.
Is that deliberate or is not going to be possible if you use the devtools?

By idea - it is not needed. Coverage should take into account every used CSS rule from my POV. But this is not the case right now.

> I'm quite excited about the idea of it giving a minimal CSS based on ALL CSS loaded into memory and not just the external CSS.

But I filtered it out

```js
const { header } = stylesheet
if (
  header.isInline ||
  header.sourceURL === '' ||
  header.sourceURL.startsWith('blob:')
) {
  inlineStylesheetIndex.add(header.styleSheetId)
}
```

**Comment by stereobooster** [comment]
> So what's the Chrome bug to pin this to?

- https://bugs.chromium.org/p/chromium/issues/detail?id=765088
- https://bugs.chromium.org/p/chromium/issues/detail?id=744202&q=css%20Coverage%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
- https://bugs.chromium.org/p/chromium/issues/detail?id=734470&q=css%20Coverage%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
- https://bugs.chromium.org/p/chromium/issues/detail?id=717195&q=css%20Coverage%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by stereobooster** [comment]
Will close for now as not actionable

**Pull request closed without merging**
